
import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Pork Isaw (3 sticks)',
    description: 'Grilled marinated pig intestines, served with spicy vinegar dip.',
    price: 45.00,
    category: 'Ihaw-Ihaw',
    image: 'https://images.unsplash.com/photo-1593759608136-44ca21eeb482?q=80&w=800',
    rating: 4.8,
    reviews: [
      { id: 'r1', userId: 'u2', userName: 'Juan D.', rating: 5, comment: 'Solid! The vinegar dip is perfect.', date: 1715420000000 },
      { id: 'r2', userId: 'u3', userName: 'Maria C.', rating: 4, comment: 'Clean and tasty.', date: 1715320000000 }
    ],
    isSpicy: false,
    isVeg: false
  },
  {
    id: '2',
    name: 'Sizzling Pork Sisig w/ Rice',
    description: 'Chopped pork face and belly with onions, chili peppers, and calamansi. Served with garlic rice.',
    price: 120.00,
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=800',
    rating: 4.9,
    reviews: [
      { id: 'r3', userId: 'u4', userName: 'Pedro P.', rating: 5, comment: 'Best pulutan and ulam!', date: 1715120000000 }
    ],
    isSpicy: true,
    isVeg: false
  },
  {
    id: '3',
    name: 'Kwek-Kwek (Order of 4)',
    description: 'Deep-fried battered quail eggs with manong sauce.',
    price: 25.00,
    category: 'Fried',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?q=80&w=800',
    rating: 4.7,
    reviews: [
       { id: 'r4', userId: 'u5', userName: 'Ana R.', rating: 4, comment: 'Crispy batter!', date: 1714920000000 }
    ],
    isSpicy: false,
    isVeg: true
  },
  {
    id: '4',
    name: 'Classic Taho',
    description: 'Warm silken tofu with arnibal (brown sugar syrup) and sago pearls.',
    price: 30.00,
    category: 'Merienda',
    image: 'https://images.unsplash.com/photo-1624554429144-c2615f810188?q=80&w=800',
    rating: 5.0,
    reviews: [],
    isSpicy: false,
    isVeg: true
  },
  {
    id: '5',
    name: 'Special Halo-Halo',
    description: 'Shaved ice dessert with ube, leche flan, sweet beans, jellies, and evaporated milk.',
    price: 85.00,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800',
    rating: 4.8,
    reviews: [],
    isSpicy: false,
    isVeg: true
  },
  {
    id: '6',
    name: 'Fishball & Kikiam Platter',
    description: 'Mixed street food favorites fried to perfection with sweet and spicy sauce.',
    price: 40.00,
    category: 'Fried',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800',
    rating: 4.5,
    reviews: [],
    isSpicy: false,
    isVeg: false
  },
  {
    id: '7',
    name: 'Chicken Inasal Pecho',
    description: 'Grilled chicken breast marinated in lemongrass, calamansi, and annatto oil.',
    price: 135.00,
    category: 'Ihaw-Ihaw',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=800',
    rating: 4.9,
    reviews: [],
    isSpicy: false,
    isVeg: false
  },
  {
    id: '8',
    name: 'Lugaw with Egg',
    description: 'Savory rice porridge topped with hard-boiled egg, garlic chips, and spring onions.',
    price: 50.00,
    category: 'Rice Meals',
    image: 'https://images.unsplash.com/photo-1558920555-17c0227c5883?q=80&w=800',
    rating: 4.6,
    reviews: [],
    isSpicy: false,
    isVeg: false
  },
  {
    id: '9',
    name: 'Turon (2 pcs)',
    description: 'Sweet banana and jackfruit wrapped in spring roll wrapper and fried with sugar glaze.',
    price: 20.00,
    category: 'Merienda',
    image: 'https://images.unsplash.com/photo-1628362365799-23546379c4e2?q=80&w=800',
    rating: 4.8,
    reviews: [],
    isSpicy: false,
    isVeg: true
  }
];

export const CATEGORIES = ['All', 'Ihaw-Ihaw', 'Rice Meals', 'Fried', 'Merienda', 'Desserts'];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    searchPlaceholder: 'Search for food...',
    aboutUs: 'About Us',
    aboutText: 'We bring you the classic taste of Filipino street food. Clean, delicious, and affordable. Order your favorites now!',
    recentSearches: 'Recent',
    clear: 'Clear',
    noFoodFound: 'No food found.',
    signUpNow: 'Sign Up Now',
    myCart: 'My Cart',
    deliveryTo: 'Delivery to:',
    emptyCartTitle: 'Your cart is empty',
    emptyCartText: 'Looks like you haven\'t made your choice yet. Let\'s browse the menu!',
    browseMenu: 'Browse Menu',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    checkout: 'Checkout',
    myOrders: 'My Orders',
    noPastOrders: 'No past orders',
    noPastOrdersText: 'You haven\'t ordered yet. Are you hungry?',
    orderNow: 'Order Now',
    orderDetails: 'Order Details',
    totalPaid: 'Total Paid',
    orderAgain: 'Order Again',
    rate: 'Rate',
    profileSettings: 'Profile & Settings',
    myFavorites: 'My Favorites',
    noFavorites: 'No favorites yet. Go explore the menu!',
    adminMode: 'Admin Mode',
    logOut: 'Log Out',
    edit: 'Edit',
    saveAddress: 'Save Address',
    cancel: 'Cancel',
    language: 'Language',
    english: 'English',
    filipino: 'Filipino',
    loginWelcome: 'Welcome Back!',
    loginText: 'Log in to continue your food journey.',
    joinFeast: 'Join the Feast',
    joinText: 'Create an account to start ordering.',
    continueGoogle: 'Continue with Google',
    or: 'OR',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone Number',
    address: 'Delivery Address',
    login: 'Log In',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',
    noAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    status_confirmed: 'Order Confirmed',
    status_preparing: 'Preparing',
    status_delivering: 'Out for Delivery',
    status_delivered: 'Delivered',
    status_arrived: 'Arrived at',
    status_estimated: 'Estimated Arrival',
    kitchen: 'Kitchen',
    driver_mins: 'mins away',
    processing: 'Processing...',
    ai_welcome: "Hey there! I'm StreetBot 🤖. Hungry? Ask me for recommendations!",
    ai_placeholder: "Ask about spicy food...",
    dashboard: "Dashboard",
    activeOrders: "Active Orders",
    revenue: "Revenue",
    avgOrder: "Avg Order",
    menuItems: "Menu Items",
    quickActions: "Quick Actions",
    manageOrders: "Manage Orders",
    addItem: "Add Item",
    addNewItem: "Add New Item",
    editItem: "Edit Item",
    saveChanges: "Save Changes",
    createItem: "Create Item",
    imageURL: "Image URL",
    name: "Name",
    price: "Price",
    category: "Category",
    description: "Description",
    spicy: "Spicy",
    veg: "Veg",
    pasteImage: "Paste Image URL below"
  },
  fil: {
    home: 'Home',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    searchPlaceholder: 'Maghanap ng pagkain...',
    aboutUs: 'Tungkol sa Amin',
    aboutText: 'Hatid namin ang classic na lasa ng Pinoy street food. Malinis, masarap, at swak sa budget. Order na!',
    recentSearches: 'Kamakailan',
    clear: 'Burahin',
    noFoodFound: 'Walang nahanap na pagkain.',
    signUpNow: 'Mag-sign Up na',
    myCart: 'Cart Ko',
    deliveryTo: 'Idedeliver sa:',
    emptyCartTitle: 'Empty pa ang cart mo',
    emptyCartText: 'Wala ka pang napipili. Tara, tingin tayo sa menu!',
    browseMenu: 'Tingin sa Menu',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    total: 'Kabuuan',
    checkout: 'Checkout',
    myOrders: 'Orders Ko',
    noPastOrders: 'Wala pang orders',
    noPastOrdersText: 'Di ka pa umoorder. Gutom ka na ba?',
    orderNow: 'Order Na',
    orderDetails: 'Detalye ng Order',
    totalPaid: 'Binayaran',
    orderAgain: 'Order Ulit',
    rate: 'I-rate',
    profileSettings: 'Profile at Settings',
    myFavorites: 'Mga Paborito',
    noFavorites: 'Wala pang favorites. Tara mag-explore!',
    adminMode: 'Admin Mode',
    logOut: 'Mag-logout',
    edit: 'Baguhin',
    saveAddress: 'I-save ang Address',
    cancel: 'Kanselahin',
    language: 'Wika',
    english: 'English',
    filipino: 'Filipino',
    loginWelcome: 'Welcome Back!',
    loginText: 'Mag-login para makakain na.',
    joinFeast: 'Sali na sa Kainaan',
    joinText: 'Gumawa ng account para maka-order.',
    continueGoogle: 'Magpatuloy gamit ang Google',
    or: 'O KAYA',
    fullName: 'Buong Pangalan',
    email: 'Email',
    phone: 'Mobile Number',
    address: 'Delivery Address',
    login: 'Mag-login',
    createAccount: 'Gumawa ng Account',
    haveAccount: 'May account ka na?',
    noAccount: 'Wala pang account?',
    signUp: 'Mag-sign Up',
    status_confirmed: 'Order Confirmed',
    status_preparing: 'Niluluto na',
    status_delivering: 'Papunta na',
    status_delivered: 'Naihatid na',
    status_arrived: 'Dumating ng',
    status_estimated: 'Darating ng',
    kitchen: 'Kusina',
    driver_mins: 'mins ang layo',
    processing: 'Pinoproseso...',
    ai_welcome: "Hello! Ako si StreetBot 🤖. Gutom ka na? Tanungin mo ako ng recommendations!",
    ai_placeholder: "Magtanong tungkol sa pagkain...",
    dashboard: "Dashboard",
    activeOrders: "Active Orders",
    revenue: "Kita",
    avgOrder: "Avg na Order",
    menuItems: "Menu Items",
    quickActions: "Mabilisang Aksyon",
    manageOrders: "Ayusin ang Orders",
    addItem: "Magdagdag",
    addNewItem: "Magdagdag ng Item",
    editItem: "Baguhin ang Item",
    saveChanges: "I-save ang Pagbabago",
    createItem: "Gawin ang Item",
    imageURL: "Link ng Litrato",
    name: "Pangalan",
    price: "Presyo",
    category: "Kategorya",
    description: "Paglalarawan",
    spicy: "Maanghang",
    veg: "Gulay",
    pasteImage: "Ilagay ang link ng litrato"
  }
};
